export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'


export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE'
export const GET_PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const GET_PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR'